// Post-build service worker generator.
// Pre-caches the app shell so the PWA opens instantly once installed.
// This app has no backend calls to worry about excluding — all data comes
// from Web Bluetooth, which service workers can't intercept anyway.

import { writeFileSync, readdirSync } from 'fs';
import { join } from 'path';
import { createHash } from 'crypto';

const DIST = 'dist';
const OUT = `${DIST}/sw.js`;

const assets = [];
try {
  for (const f of readdirSync(join(DIST, 'assets'))) {
    assets.push(`/assets/${f}`);
  }
} catch {}
assets.push('/', '/manifest.json');

const version = createHash('md5').update(assets.join(',')).digest('hex').slice(0, 8);
const cacheName = `victron-dashboard-bt-v${version}`;

const sw = `// Auto-generated by scripts/gen-sw.mjs — do not edit
const CACHE_NAME = '${cacheName}';
const PRECACHE_URLS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      await Promise.allSettled(
        PRECACHE_URLS.map((url) =>
          cache.add(url).catch((err) => console.warn('[SW] Failed to pre-cache:', url, err))
        )
      );
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((n) => n !== CACHE_NAME).map((n) => caches.delete(n)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        if (response && response.status === 200 && response.type === 'basic') {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
        }
        return response;
      });
    })
  );
});
`;

writeFileSync(OUT, sw);
console.log(`[gen-sw] wrote ${OUT} (cache: ${cacheName}, ${assets.length} pre-cached URLs)`);
